// TO DO
//need to add Danza

export const godArray = [
{name: 'Achilles', type: 'Physical',  image: 'godimages/achilles.jpeg'},
{name: 'Agni', type: 'Magic',  image: 'godimages/agni.jpeg'},
{name: 'Ah Muzen Cab', type: 'Physical',  image: 'godimages/ahmuzencab.jpeg'},
{name: 'Ah Puch', type: 'Magic',  image: 'godimages/ahpuch.jpeg'},
{name: 'Amaterasu', type: 'Physical',  image: 'godimages/amaterasu.jpeg'},
{name: 'Anhur', type: 'Physical',  image: 'godimages/anhur.jpeg'},
{name: 'Anubis', type: 'Magic',  image: 'godimages/anubis.jpeg'},
{name: 'Ao Kuang', type: 'Magic',  image: 'godimages/aokuang.jpeg'},
{name: 'Aphrodite', type: 'Magic',  image: 'godimages/aphrodite.jpeg'},
{name: 'Apollo', type: 'Physical',  image: 'godimages/apollo.jpeg'},
{name: 'Arachne', type: 'Physical',  image: 'godimages/arachne.jpeg'},
{name: 'Ares', type: 'Magic',  image: 'godimages/ares.jpeg'},
{name: 'Artemis', type: 'Physical',  image: 'godimages/artemis.jpeg'},
{name: 'Artio', type: 'Magic',  image: 'godimages/artio.jpeg'},
{name: 'Athena', type: 'Magic',  image: 'godimages/athena.jpeg'},
{name: 'Awilix', type: 'Physical',  image: 'godimages/awilix.jpeg'},
{name: 'Baba Yaga', type: 'Magic',  image: 'godimages/babayaga.jpeg'},
{name: 'Bacchus', type: 'Magic',  image: 'godimages/bacchus.jpeg'},
{name: 'Bakasura', type: 'Physical',  image: 'godimages/bakasura.jpeg'},
{name: 'Baron Samedi', type: 'Magic',  image: 'godimages/baronsamedi.jpeg'},
{name: 'Bastet', type: 'Physical',  image: 'godimages/bastet.jpeg'},
{name: 'Bellona', type: 'Physical',  image: 'godimages/bellona.jpeg'},
{name: 'Cabrakan', type: 'Magic',  image: 'godimages/cabrakan.jpeg'},
{name: 'Camazotz', type: 'Physical',  image: 'godimages/camazotz.jpeg'},
{name: 'Cerberus', type: 'Magic',  image: 'godimages/cerberus.jpeg'},
{name: 'Cernunnos', type: 'Physical',  image: 'godimages/cernunnos.jpeg'},
{name: 'Chaac', type: 'Physical',  image: 'godimages/chaac.jpeg'},
{name: 'Chang\'e', type: 'Magic',  image: 'godimages/change.jpeg'},
{name: 'Chernobog', type: 'Physical',  image: 'godimages/chernobog.jpeg'},
{name: 'Chiron', type: 'Physical',  image: 'godimages/chiron.jpeg'},
{name: 'Chronos', type: 'Magic',  image: 'godimages/chronos.jpeg'},
{name: 'Cthulhu', type: 'Magic',  image: 'godimages/cthulhu.jpeg'},
{name: 'Cu Chulainn', type: 'Physical',  image: 'godimages/cuchulainn.jpeg'},
{name: 'Cupid', type: 'Physical',  image: 'godimages/cupid.jpeg'},
{name: 'Da Ji', type: 'Physical',  image: 'godimages/daji.jpeg'},
{name: 'Discordia', type: 'Magic',  image: 'godimages/discordia.jpeg'},
{name: 'Erlang Shen', type: 'Physical',  image: 'godimages/erlangshen.jpeg'},
{name: 'Fafnir', type: 'Magic',  image: 'godimages/fafnir.jpeg'},
{name: 'Fenrir', type: 'Physical',  image: 'godimages/fenrir.jpeg'},
{name: 'Freya', type: 'Magic',  image: 'godimages/freya.jpeg'},
{name: 'Ganesha', type: 'Magic',  image: 'godimages/ganesha.jpeg'},
{name: 'Geb', type: 'Magic',  image: 'godimages/geb.jpeg'},
{name: 'Guan Yu', type: 'Physical',  image: 'godimages/guanyu.jpeg'},
{name: 'Hachiman', type: 'Physical',  image: 'godimages/hachiman.jpeg'},
{name: 'Hades', type: 'Magic',  image: 'godimages/hades.jpeg'},
{name: 'He Bo', type: 'Magic',  image: 'godimages/hebo.jpeg'},
{name: 'Heimdallr', type: 'Physical',  image: 'godimages/heimdallr.jpeg'},
{name: 'Hel', type: 'Magic',  image: 'godimages/hel.jpeg'},
{name: 'Hera', type: 'Magic',  image: 'godimages/hera.jpeg'},
{name: 'Hercules', type: 'Physical',  image: 'godimages/hercules.jpeg'},
{name: 'Horus', type: 'Physical',  image: 'godimages/horus.jpeg'},
{name: 'Hou Yi', type: 'Physical',  image: 'godimages/houyi.jpeg'},
{name: 'Hun Batz', type: 'Physical',  image: 'godimages/hunbatz.jpeg'},
{name: 'Isis', type: 'Magic',  image: 'godimages/isis.jpeg'},
{name: 'Izanami', type: 'Physical',  image: 'godimages/izanami.jpeg'},
{name: 'Janus', type: 'Magic',  image: 'godimages/janus.jpeg'},
{name: 'Jing Wei', type: 'Physical',  image: 'godimages/jingwei.jpeg'},
{name: 'Jormungandr', type: 'Magic',  image: 'godimages/jormungandr.jpeg'},
{name: 'Kali', type: 'Physical',  image: 'godimages/kali.jpeg'},
{name: 'Khepri', type: 'Magic',  image: 'godimages/khepri.jpeg'},
{name: 'King Arthur', type: 'Physical',  image: 'godimages/kingarthur.jpeg'},
{name: 'Kukulkan', type: 'Magic',  image: 'godimages/kukulkan.jpeg'},
{name: 'Kumbhakarna', type: 'Magic',  image: 'godimages/kumbhakarna.jpeg'},
{name: 'Kuzenbo', type: 'Magic',  image: 'godimages/kuzenbo.jpeg'},
{name: 'Loki', type: 'Physical',  image: 'godimages/loki.jpeg'},
{name: 'Medusa', type: 'Physical',  image: 'godimages/medusa.jpeg'},
{name: 'Mercury', type: 'Physical',  image: 'godimages/mercury.jpeg'},
{name: 'Merlin', type: 'Magic',  image: 'godimages/merlin.jpeg'},
{name: 'Mulan', type: 'Physical',  image: 'godimages/mulan.jpeg'},
{name: 'Ne Zha', type: 'Physical',  image: 'godimages/nezha.jpeg'},
{name: 'Neith', type: 'Physical',  image: 'godimages/neith.jpeg'},
{name: 'Nemesis', type: 'Physical',  image: 'godimages/nemesis.jpeg'},
{name: 'Nike', type: 'Physical',  image: 'godimages/nike.jpeg'},
{name: 'Nox', type: 'Magic',  image: 'godimages/nox.jpeg'},
{name: 'Nu Wa', type: 'Magic',  image: 'godimages/nuwa.jpeg'},
{name: 'Odin', type: 'Physical',  image: 'godimages/odin.jpeg'},
{name: 'Olorun', type: 'Magic',  image: 'godimages/olorun.jpeg'},
{name: 'Osiris', type: 'Physical',  image: 'godimages/osiris.jpeg'},
{name: 'Pele', type: 'Physical',  image: 'godimages/pele.jpeg'},
{name: 'Persephone', type: 'Magic',  image: 'godimages/persephone.jpeg'},
{name: 'Poseidon', type: 'Magic',  image: 'godimages/poseidon.jpeg'},
{name: 'Ra', type: 'Magic',  image: 'godimages/ra.jpeg'},
{name: 'Raijin', type: 'Magic',  image: 'godimages/raijin.jpeg'},
{name: 'Rama', type: 'Physical',  image: 'godimages/rama.jpeg'},
{name: 'Ratatoskr', type: 'Physical',  image: 'godimages/ratatoskr.jpeg'},
{name: 'Ravana', type: 'Physical',  image: 'godimages/ravana.jpeg'},
{name: 'Scylla', type: 'Magic',  image: 'godimages/scylla.jpeg'},
{name: 'Serqet', type: 'Physical',  image: 'godimages/serqet.jpeg'},
{name: 'Set', type: 'Physical',  image: 'godimages/set.jpeg'},
{name: 'Skadi', type: 'Physical',  image: 'godimages/skadi.jpeg'},
{name: 'Sobek', type: 'Magic',  image: 'godimages/sobek.jpeg'},
{name: 'Sol', type: 'Magic',  image: 'godimages/sol.jpeg'},
{name: 'Sun Wukong', type: 'Physical',  image: 'godimages/sunwukong.jpeg'},
{name: 'Susano', type: 'Physical',  image: 'godimages/susano.jpeg'},
{name: 'Sylvanus', type: 'Magic',  image: 'godimages/sylvanus.jpeg'},
{name: 'Terra', type: 'Magic',  image: 'godimages/terra.jpeg'},
{name: 'Thanatos', type: 'Physical',  image: 'godimages/thanatos.jpeg'},
{name: 'The Morrigan', type: 'Magic',  image: 'godimages/themorrigan.jpeg'},
{name: 'Thor', type: 'Physical',  image: 'godimages/thor.jpeg'},
{name: 'Thoth', type: 'Magic',  image: 'godimages/thoth.jpeg'},
{name: 'Tsukuyomi', type: 'Physical',  image: 'godimages/tsukuyomi.jpeg'},
{name: 'Tyr', type: 'Physical',  image: 'godimages/tyr.jpeg'},
{name: 'Ullr', type: 'Physical',  image: 'godimages/ullr.jpeg'},
{name: 'Vamana', type: 'Physical',  image: 'godimages/vamana.jpeg'},
{name: 'Vulcan', type: 'Magic',  image: 'godimages/vulcan.jpeg'},
{name: 'Xbalanque', type: 'Physical',  image: 'godimages/xbalanque.jpeg'},
{name: 'Xing Tian', type: 'Magic',  image: 'godimages/xingtian.jpeg'},
{name: 'Yemoja', type: 'Magic',  image: 'godimages/yemoja.jpeg'},
{name: 'Ymir', type: 'Magic',  image: 'godimages/ymir.jpeg'},
{name: 'Zeus', type: 'Magic',  image: 'godimages/zeus.jpeg'},
{name: 'Zhong Kui', type: 'Magic',  image: 'godimages/zhongkui.jpeg'}
];


export const itemArray = [
{name: 'Sovereignty', type: 'Both'},
{name: 'Mystical Mail', type: 'Both'},
{name: 'Midgardian Mail', type: 'Both'},
{name: 'Emperor\'s Armor', type: 'Both'},
{name: 'The Executioner', type: 'Physical'},
{name: 'Quin\'s Sais', type: 'Physical'},
{name: 'Asi', type: 'Physical'},
{name: 'Pythagorem\'s Piece', type: 'Magic'},
{name: 'Bancroft\'s Talon', type: 'Magic'},
{name: 'Typhon\'s Fang', type: 'Magic'},
{name: 'Soul Gem', type: 'Magic'},
{name: 'Titan\'s Bane', type: 'Physical'},
{name: 'Brawler\'s Beat Stick', type: 'Physical'},
{name: 'Jotunn\'s Wrath', type: 'Physical'},
{name: 'The Crusher', type: 'Physical'},
{name: 'Transcendence', type: 'Physical'},
{name: 'Hydra\'s Lament', type: 'Physical'},
{name: 'Heartseeker', type: 'Physical'},
{name: 'Deathbringer', type: 'Physical'},
{name: 'Rage', type: 'Physical'},
{name: 'Malice', type: 'Physical'},
{name: 'Soul Eater', type: 'Physical'},
{name: 'Devourer\'s Gauntlet', type: 'Physical'},
{name: 'Bloodforge', type: 'Physical'},
{name: 'Witchblade', type: 'Both'},
{name: 'Winged Blade', type: 'Both'},
{name: 'Relic Dagger', type: 'Both'},
{name: 'Frostbound Hammer', type: 'Physical'},
{name: 'Runeforged Hammer', type: 'Physical'},
{name: 'The Sledge', type: 'Physical'},
{name: 'Blackthorn Hammer', type: 'Physical'},
{name: 'Shifter\'s Shield', type: 'Physical'},
{name: 'Void Shield', type: 'Physical'},
{name: 'Gladiator\'s Shield', type: 'Physical'},
{name: 'Berserker\'s Shield', type: 'Physical'},
{name: 'Hide of the Nemean Lion', type: 'Both'},
{name: 'Breastplate of Valor', type: 'Both'},
{name: 'Spectral Armor', type: 'Both'},
{name: 'Contagion', type: 'Both'},
{name: 'Magi\'s Cloak', type: 'Both'},
{name: 'Hide of the Urchin', type: 'Both'},
{name: 'Spirit Robe', type: 'Both'},
{name: 'Mantle of Discord', type: 'Both'},
{name: 'Bulwark of Hope', type: 'Both'},
{name: 'Pestilence', type: 'Both'},
{name: 'Heartward Amulet', type: 'Both'},
{name: 'Talisman of Energy', type: 'Both'},
{name: 'Demonic Grip', type: 'Magic'},
{name: 'Telkhines Ring', type: 'Magic'},
{name: 'Hastened Ring', type: 'Magic'},
{name: 'Ring of Hecate', type: 'Magic'},
{name: 'Divine Ruin', type: 'Magic'},
{name: 'Spear of Desolation', type: 'Magic'},
{name: 'Obsidian Shard', type: 'Magic'},
{name: 'Spear of the Magus', type: 'Magic'},
{name: 'Gem of Isolation', type: 'Magic'},
{name: 'Warlock\'s Staff', type: 'Magic'},
{name: 'Ethereal Staff', type: 'Magic'},
{name: 'Rod of Asclepius', type: 'Magic'},
{name: 'Book of Thoth', type: 'Magic'},
{name: 'Soul Reaver', type: 'Magic'},
{name: 'Polynomicon', type: 'Magic'},
{name: 'Book of the Dead', type: 'Magic'},
{name: 'Rod of Tahuti', type: 'Magic'},
{name: 'Chronos\' Pendant', type: 'Magic'},
{name: 'Doom Orb', type: 'Magic'},
{name: 'Charon\'s Coin', type: 'Magic'},
{name: 'Runic Shield', type: 'Physical'},
{name: 'Ancile', type: 'Physical'},
{name: 'Caduceus Shield', type: 'Physical'},
{name: 'Celestial Legion Helm', type: 'Magic'},
{name: 'Lotus Crown', type: 'Magic'},
{name: 'Jade Emperor\'s Crown', type: 'Magic'},
{name: 'Tyrannical Plate Helm', type: 'Magic'},
{name: 'Odysseus\' Bow', type: 'Physical'},
{name: 'Ichaival', type: 'Physical'},
{name: 'Silverbranch Bow', type: 'Physical'},
{name: 'Atalanta\'s Bow', type: 'Physical'},
{name: 'Stone of Gaia', type: 'Both'},
{name: 'Shield of Regrowth', type: 'Both'},
{name: 'Mail of Renewal', type: 'Both'},
{name: 'Gauntlet of Thebes', type: 'Both'},
{name: 'Wind Demon', type: 'Physical'},
{name: 'Poisoned Star', type: 'Physical'},
{name: 'Shadowsteel Shuriken', type: 'Physical'},
{name: 'Stone Cutting Sword', type: 'Physical'},
{name: 'Hastened Katana', type: 'Physical'},
{name: 'Golden Blade', type: 'Physical'},
{name: 'Serrated Edge', type: 'Physical'},
{name: 'Genji\'s Guard', type: 'Both'},
{name: 'Oni Hunter\'s Garb', type: 'Both'},
{name: 'Shogun\'s Kusari', type: 'Both'},
{name: 'Void Stone', type: 'Magic'},
{name: 'Stone of Fal', type: 'Magic'},
//{name: 'Bumba\'s Mask', type: ''},
{name: 'Staff of Myrddin', type: 'Magic'},
{name: 'Pridwen', type: 'Both'},
{name: 'Arondight', type: 'Physical'},
{name: 'Fail-Not', type: 'Physical'},
{name: 'Stone of Binding', type: 'Magic'},
{name: 'Dynasty Plate Helm', type: 'Magic'}
];

