export const godArray = [
    {id: 'achilles', name: 'Achilles', type: 'Physical',  image: 'godimages/achilles.jpeg'},
    {id: 'Agni',name: 'Agni', type: 'Magic',  image: 'godimages/agni.jpeg'},
    {id: 'ahmuzencab',name: 'Ah Muzen Cab', type: 'Physical',  image: 'godimages/ahmuzencab.jpeg'},
    {id: 'ahpuch',name: 'Ah Puch', type: 'Magic',  image: 'godimages/ahpuch.jpeg'},
    {id: 'amaterasu',name: 'Amaterasu', type: 'Physical',  image: 'godimages/amaterasu.jpeg'},
    {id: 'anhur',name: 'Anhur', type: 'Physical',  image: 'godimages/anhur.jpeg'},
    {id: 'anubis',name: 'Anubis', type: 'Magic',  image: 'godimages/anubis.jpeg'},
    {id: 'aokuang',name: 'Ao Kuang', type: 'Magic',  image: 'godimages/aokuang.jpeg'},
    {id: 'aphrodite',name: 'Aphrodite', type: 'Magic',  image: 'godimages/aphrodite.jpeg'},
    {id: 'apollo',name: 'Apollo', type: 'Physical',  image: 'godimages/apollo.jpeg'},
    {id: 'arachne',name: 'Arachne', type: 'Physical',  image: 'godimages/arachne.jpeg'},
    {id: 'ares',name: 'Ares', type: 'Magic',  image: 'godimages/ares.jpeg'},
    {id: 'artemis',name: 'Artemis', type: 'Physical',  image: 'godimages/artemis.jpeg'},
    {id: 'artio',name: 'Artio', type: 'Magic',  image: 'godimages/artio.jpeg'},
    {id: 'athena',name: 'Athena', type: 'Magic',  image: 'godimages/athena.jpeg'},
    {id: 'awilix',name: 'Awilix', type: 'Physical',  image: 'godimages/awilix.jpeg'},
    {id: 'babayaga',name: 'Baba Yaga', type: 'Magic',  image: 'godimages/babayaga.jpeg'},
    {id: 'bacchus',name: 'Bacchus', type: 'Magic',  image: 'godimages/bacchus.jpeg'},
    {id: 'bakasura',name: 'Bakasura', type: 'Physical',  image: 'godimages/bakasura.jpeg'},
    {id: 'baronsamedi',name: 'Baron Samedi', type: 'Magic',  image: 'godimages/baronsamedi.jpeg'},
    {id: 'bastet',name: 'Bastet', type: 'Physical',  image: 'godimages/bastet.jpeg'},
    {id: 'bellona',name: 'Bellona', type: 'Physical',  image: 'godimages/bellona.jpeg'},
    {id: 'cabrakan',name: 'Cabrakan', type: 'Magic',  image: 'godimages/cabrakan.jpeg'},
    {id: 'camazotz',name: 'Camazotz', type: 'Physical',  image: 'godimages/camazotz.jpeg'},
    {id: 'cerberus',name: 'Cerberus', type: 'Magic',  image: 'godimages/cerberus.jpeg'},
    {id: 'cernunnos',name: 'Cernunnos', type: 'Physical',  image: 'godimages/cernunnos.jpeg'},
    {id: 'chaac',name: 'Chaac', type: 'Physical',  image: 'godimages/chaac.jpeg'},
    {id: 'change',name: 'Chang\'e', type: 'Magic',  image: 'godimages/change.jpeg'},
    {id: 'chernobog',name: 'Chernobog', type: 'Physical',  image: 'godimages/chernobog.jpeg'},
    {id: 'chiron',name: 'Chiron', type: 'Physical',  image: 'godimages/chiron.jpeg'},
    {id: 'chronos',name: 'Chronos', type: 'Magic',  image: 'godimages/chronos.jpeg'},
    {id: 'cthulu',name: 'Cthulhu', type: 'Magic',  image: 'godimages/cthulhu.jpeg'},
    {id: 'cuchulainn',name: 'Cu Chulainn', type: 'Physical',  image: 'godimages/cuchulainn.jpeg'},
    {id: 'cupid',name: 'Cupid', type: 'Physical',  image: 'godimages/cupid.jpeg'},
    {id: 'daji',name: 'Da Ji', type: 'Physical',  image: 'godimages/daji.jpeg'},
    {id: 'discordia',name: 'Discordia', type: 'Magic',  image: 'godimages/discordia.jpeg'},
    {id: 'erlangshen',name: 'Erlang Shen', type: 'Physical',  image: 'godimages/erlangshen.jpeg'},
    {id: 'fafnir',name: 'Fafnir', type: 'Magic',  image: 'godimages/fafnir.jpeg'},
    {id: 'fenrir',name: 'Fenrir', type: 'Physical',  image: 'godimages/fenrir.jpeg'},
    {id: 'freya',name: 'Freya', type: 'Magic',  image: 'godimages/freya.jpeg'},
    {id: 'ganesha',name: 'Ganesha', type: 'Magic',  image: 'godimages/ganesha.jpeg'},
    {id: 'geb',name: 'Geb', type: 'Magic',  image: 'godimages/geb.jpeg'},
    {id: 'guanyu',name: 'Guan Yu', type: 'Physical',  image: 'godimages/guanyu.jpeg'},
    {id: 'hachiman',name: 'Hachiman', type: 'Physical',  image: 'godimages/hachiman.jpeg'},
    {id: 'hades',name: 'Hades', type: 'Magic',  image: 'godimages/hades.jpeg'},
    {id: 'hebo',name: 'He Bo', type: 'Magic',  image: 'godimages/hebo.jpeg'},
    {id: 'heimdallr',name: 'Heimdallr', type: 'Physical',  image: 'godimages/heimdallr.jpeg'},
    {id: 'hel',name: 'Hel', type: 'Magic',  image: 'godimages/hel.jpeg'},
    {id: 'hera',name: 'Hera', type: 'Magic',  image: 'godimages/hera.jpeg'},
    {id: 'hercules',name: 'Hercules', type: 'Physical',  image: 'godimages/hercules.jpeg'},
    {id: 'horus',name: 'Horus', type: 'Physical',  image: 'godimages/horus.jpeg'},
    {id: 'houyi',name: 'Hou Yi', type: 'Physical',  image: 'godimages/houyi.jpeg'},
    {id: 'hunbatz',name: 'Hun Batz', type: 'Physical',  image: 'godimages/hunbatz.jpeg'},
    {id: 'isis',name: 'Isis', type: 'Magic',  image: 'godimages/isis.jpeg'},
    {id: 'izanami',name: 'Izanami', type: 'Physical',  image: 'godimages/izanami.jpeg'},
    {id: 'janus',name: 'Janus', type: 'Magic',  image: 'godimages/janus.jpeg'},
    {id: 'jingwei',name: 'Jing Wei', type: 'Physical',  image: 'godimages/jingwei.jpeg'},
    {id: 'jormungandr',name: 'Jormungandr', type: 'Magic',  image: 'godimages/jormungandr.jpeg'},
    {id: 'kali',name: 'Kali', type: 'Physical',  image: 'godimages/kali.jpeg'},
    {id: 'khepri',name: 'Khepri', type: 'Magic',  image: 'godimages/khepri.jpeg'},
    {id: 'kingarthur',name: 'King Arthur', type: 'Physical',  image: 'godimages/kingarthur.jpeg'},
    {id: 'kukulkan',name: 'Kukulkan', type: 'Magic',  image: 'godimages/kukulkan.jpeg'},
    {id: 'kumbhakarna',name: 'Kumbhakarna', type: 'Magic',  image: 'godimages/kumbhakarna.jpeg'},
    {id: 'kuzenbo',name: 'Kuzenbo', type: 'Magic',  image: 'godimages/kuzenbo.jpeg'},
    {id: 'loki',name: 'Loki', type: 'Physical',  image: 'godimages/loki.jpeg'},
    {id: 'medusa',name: 'Medusa', type: 'Physical',  image: 'godimages/medusa.jpeg'},
    {id: 'mercury',name: 'Mercury', type: 'Physical',  image: 'godimages/mercury.jpeg'},
    {id: 'merlin',name: 'Merlin', type: 'Magic',  image: 'godimages/merlin.jpeg'},
    {id: 'mulan',name: 'Mulan', type: 'Physical',  image: 'godimages/mulan.jpeg'},
    {id: 'nezha',name: 'Ne Zha', type: 'Physical',  image: 'godimages/nezha.jpeg'},
    {id: 'neith',name: 'Neith', type: 'Physical',  image: 'godimages/neith.jpeg'},
    {id: 'nemesis',name: 'Nemesis', type: 'Physical',  image: 'godimages/nemesis.jpeg'},
    {id: 'nike',name: 'Nike', type: 'Physical',  image: 'godimages/nike.jpeg'},
    {id: 'nox',name: 'Nox', type: 'Magic',  image: 'godimages/nox.jpeg'},
    {id: 'nuwa',name: 'Nu Wa', type: 'Magic',  image: 'godimages/nuwa.jpeg'},
    {id: 'odin',name: 'Odin', type: 'Physical',  image: 'godimages/odin.jpeg'},
    {id: 'olorun',name: 'Olorun', type: 'Magic',  image: 'godimages/olorun.jpeg'},
    {id: 'osiris',name: 'Osiris', type: 'Physical',  image: 'godimages/osiris.jpeg'},
    {id: 'pele',name: 'Pele', type: 'Physical',  image: 'godimages/pele.jpeg'},
    {id: 'persephone',name: 'Persephone', type: 'Magic',  image: 'godimages/persephone.jpeg'},
    {id: 'poseidon',name: 'Poseidon', type: 'Magic',  image: 'godimages/poseidon.jpeg'},
    {id: 'ra',name: 'Ra', type: 'Magic',  image: 'godimages/ra.jpeg'},
    {id: 'raijin',name: 'Raijin', type: 'Magic',  image: 'godimages/raijin.jpeg'},
    {id: 'rama',name: 'Rama', type: 'Physical',  image: 'godimages/rama.jpeg'},
    {id: 'ratatoskr',name: 'Ratatoskr', type: 'Physical',  image: 'godimages/ratatoskr.jpeg'},
    {id: 'ravana',name: 'Ravana', type: 'Physical',  image: 'godimages/ravana.jpeg'},
    {id: 'scylla',name: 'Scylla', type: 'Magic',  image: 'godimages/scylla.jpeg'},
    {id: 'serqet',name: 'Serqet', type: 'Physical',  image: 'godimages/serqet.jpeg'},
    {id: 'set',name: 'Set', type: 'Physical',  image: 'godimages/set.jpeg'},
    {id: 'skadi',name: 'Skadi', type: 'Physical',  image: 'godimages/skadi.jpeg'},
    {id: 'sobek',name: 'Sobek', type: 'Magic',  image: 'godimages/sobek.jpeg'},
    {id: 'sol',name: 'Sol', type: 'Magic',  image: 'godimages/sol.jpeg'},
    {id: 'sunwukong',name: 'Sun Wukong', type: 'Physical',  image: 'godimages/sunwukong.jpeg'},
    {id: 'susano',name: 'Susano', type: 'Physical',  image: 'godimages/susano.jpeg'},
    {id: 'sylvanus',name: 'Sylvanus', type: 'Magic',  image: 'godimages/sylvanus.jpeg'},
    {id: 'terra',name: 'Terra', type: 'Magic',  image: 'godimages/terra.jpeg'},
    {id: 'thanatos',name: 'Thanatos', type: 'Physical',  image: 'godimages/thanatos.jpeg'},
    {id: 'themorrigan',name: 'The Morrigan', type: 'Magic',  image: 'godimages/themorrigan.jpeg'},
    {id: 'thor',name: 'Thor', type: 'Physical',  image: 'godimages/thor.jpeg'},
    {id: 'thoth',name: 'Thoth', type: 'Magic',  image: 'godimages/thoth.jpeg'},
    {id: 'tsukuyomi',name: 'Tsukuyomi', type: 'Physical',  image: 'godimages/tsukuyomi.jpeg'},
    {id: 'tyr',name: 'Tyr', type: 'Physical',  image: 'godimages/tyr.jpeg'},
    {id: 'ullr',name: 'Ullr', type: 'Physical',  image: 'godimages/ullr.jpeg'},
    {id: 'vamana',name: 'Vamana', type: 'Physical',  image: 'godimages/vamana.jpeg'},
    {id: 'vulcan',name: 'Vulcan', type: 'Magic',  image: 'godimages/vulcan.jpeg'},
    {id: 'xbalanque',name: 'Xbalanque', type: 'Physical',  image: 'godimages/xbalanque.jpeg'},
    {id: 'xingtian',name: 'Xing Tian', type: 'Magic',  image: 'godimages/xingtian.jpeg'},
    {id: 'yemoja',name: 'Yemoja', type: 'Magic',  image: 'godimages/yemoja.jpeg'},
    {id: 'ymir',name: 'Ymir', type: 'Magic',  image: 'godimages/ymir.jpeg'},
    {id: 'zeus',name: 'Zeus', type: 'Magic',  image: 'godimages/zeus.jpeg'},
    {id: 'zhongkui',name: 'Zhong Kui', type: 'Magic',  image: 'godimages/zhongkui.jpeg'}
    ];